[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"
#  Set NEXT_PUBLIC_APP_URL in the Netlify UI to your actual site URL.
#  Example: https://ksrlearner.netlify.app

# Do NOT add SPA redirects for Next.js App Router; the plugin manages routing.

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
